/*
 * This source file was generated by the Gradle 'init' task
 */
package server;

public class App {
    public static void main(String[] args) {
        // Iniciar la estación meteorológica
        Thread estacionThread = new Thread(() -> {
            EstacionMeteorologicaUDP.main(args);
        });

        estacionThread.start();

        try {
            // Esperar indefinidamente para mantener la aplicación en ejecución
            estacionThread.join();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}
